### ISSUE TITLE
Default Rounding of Final Decimal Places.

### ISSUE THREAD

**Issue by PowerUser1234** [Qalculate/qalculate-gtk#324] opened 2021-09-15 04:47 UTC
The latest, bundled binary 64 bit form of the Qalculate! program performs default rounding of the final decimal places, without
request, and with no second option.  What I require is truncation of the results value, with absolutely no further
consideration or rounding, whatsoever.

As an example, presently, if asked to evaluate 1/6, to some stipulated precision that includes at least 2 decimal places,
the last decimal place given of this small expression is 7, when it should be 6 and just truncated at that point, as an initial example.

At any rate, there should be an easily accessed setting and configuration file option to always leave the decimal place(s),
or the Right Hand Side (RHS) of the value truncated alone, and never altered any further.  Particularly since Qalculate seems
to store and normalise the expression, and not just value evaluations, for the purpose of the inverse of an expression,
leading to an accurate, equating, beginning value(s).

Is it possible that such an option be implemented, particularly in 64 bit Qalculate? What does an involved developer
or respondee think?

**Comment by hanna-kn** [comment] 2021-09-21 11:23
Duplicate of https://github.com/Qalculate/libqalculate/issues/329

**Closed by hanna-kn** 2021-09-21 11:23 UTC
