### ISSUE TITLE
Bug: window closes after typing a simple calculation

### ISSUE THREAD

**Issue by delta211** [Qalculate/qalculate-gtk#138] opened 2020-03-26 11:37 UTC
The Qualculate window closes few seconds after typing tan(cos(0.75)) without giving a result. Is it my problem or a common bug?

**Edit:** very sorry, it was tan(**a**cos(0.75))

**Comment by hanna-kn** [comment] 2020-03-26 11:57
I am unable to reproduce this issue. Which version are you using?

**Comment by delta211** [comment] 2020-03-26 12:00
3.8.0-1
Thanks for a quick reply.

**Comment by hanna-kn** [comment] 2020-03-27 15:57
This has now been fixed in libqalculate.

You can avoid the issue by setting angle unit to radians (the result will be the same).

**Closed by hanna-kn** 2020-03-27 15:57 UTC
