### ISSUE TITLE
App takes long to start

### ISSUE THREAD

**Issue by derei** [Qalculate/qalculate-gtk#194] opened 2020-10-08 14:56 UTC
I'm also running SpeedCrunch calculator on my computer and I noticed that Qualculate takes considerably long to start, compared to SpeedCrunch. About 3x longer, which makes it noticeable.
Perhaps some features could be loaded after the program has started, or when the user is accessing them, to speed up the launch?

**Comment by hanna-kn** [comment] 2020-10-08 15:50
Duplicate of #181

**Closed** 2020-10-09 07:58 UTC
