### ISSUE TITLE
Accuracy lose in some certain cases

### ISSUE THREAD

**Issue by nick87720z** [Qalculate/qalculate-gtk#43] opened 2018-01-23 04:14 UTC
When i try to build elliptise as second order curve, supplying it as two functions for lower/upper arc, even with samples 50000 ends appear like straight.
![screenshot_2018-01-23_09-03-02](https://user-images.githubusercontent.com/3896190/35257842-8850dcfc-001d-11e8-819b-5f48952372e5.png)
While doing in gnuplot:
```
gnuplot> set samples 10000
gnuplot> plot -sqrt(2-(x**2)/2)-2, sqrt(2-(x**2)/2)-2
```
I get clear arc (setting samples to 100000 almost makes invisible gaps in end, though also slowdowns gnuplot itself).

Upd. When building qalcualte data with external gnuplot, it is as amazing, as just building funcs in gnuplot:
![screenshot_gnuplot-data](https://user-images.githubusercontent.com/3896190/35257984-7baa3d58-001e-11e8-97ee-f7f5693c67f9.png)

**Comment by hanna-kn** [comment] 2018-01-23 08:49
Qalculate! did not set Gnuplot samples, which meant that with curve smoothing, the number of samples used by  Gnuplot was reduced (with smoothing set to none the ends should not have appeared straight). This has now been fixed in libqalculate.

The gaps at the ends is caused by Qalculate! missing the extreme values (x=2; -2). It goes from x=1.997 to x=2.003 (for which y is a complex value which cannot be displayed in the plot), with range -3..3 and one thousand samples. This issue disappears if range is set to -2..2 or step size is used. A variable sample rate will lessen the issue.

**Comment by nick87720z** [comment] 2018-01-24 03:08
Hm... but there are data files remaining after qalculate plot run. Second screenshot features bare gnuplot, loading these datafiles with
`plot 'filename'` - two files for each arc. Btw, similar problem appears in exported svg - some parts appear with a bit visible flattness, and much lower number of points, than if rendered by bare gnuplot.
I guess, it relates to this issue too.

**Comment by hanna-kn** [comment] 2018-01-24 08:58
This is what happens:
Qalculate! calculates the values for the function using the specified range and number of samples (or step size) and writes the values to a file. Qalculate! sends commands to Gnuplot through a pipe and tells Gnuplot to read data from the file.
If smoothing (this is not the same as antialias and is off be default) has been set for the function in the plot dialog of qalculate-gtk, Gnuplot will calculate new data values, using the data from the file and the specified algorithm, to create a smooth line. 
It is apparently possible (which I was not aware of) that Gnuplot will calculate a lower number of new data points than provided, which might instead result in a less smooth curve, unless the Gnuplot samples variable is explicitly set to higher value.

I advice against using smoothing for functions with a high sampling rate (>= 1000), since it will only make the the data less accurate.

**Closed** 2018-03-28 11:37 UTC
