### ISSUE TITLE
How to change the language?

### ISSUE THREAD

**Issue by phourglass** [Qalculate/qalculate-gtk#78] opened 2019-01-20 12:31 UTC
Hello,

I apologize in advance if the answer is so obvious that I cannot see it.
I am trying to use qalculate on windows in France for scientific applications.

As all other scientific software I use are in english (some don't have translations anyways), 
I would like to set the qalculate language to english. I don't want to change the operating system locale to english.

Is there a way to force the language in qalculate? or by editing the cfg files? or by creating some environment variables?...

Thanks!
Philippe

**Comment by hanna-kn** [comment] 2019-01-26 21:10
I'm sorry for the late response (the issue is in the correct place).

The only way I know to not use the local language on Windows is to remove the corresponding files in the Qalculate/locale directory (remove c:\Program Files (x86)\Qalculate\locale\fr).

**Comment by hanna-kn** [comment] 2019-04-03 06:28
Version 3.0 adds an option (in the preferences dialog) to ignore the system language (and use English).

**Comment by phourglass** [comment] 2019-04-03 17:50
Hello,

Thanks you that that.
I tried it but for some reason, it did not work completely.
I selected ignore system language, restarted the application (and even the PC just in case).
File, Edit, Mode and Help are now in Engligh.
Functions Variables and Units are still in French.
On Win 10 x64.

Thanks.
Philippe

**Comment by hanna-kn** [comment] 2019-04-03 19:56
I obviously had not tested that it works on Windows. It turns out it does not. This has now been fixed (the next version will be released in approximately two weeks).

**Closed by hanna-kn** 2019-04-03 19:56 UTC
