### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by hughh** [Qalculate/qalculate-gtk#87] opened 2019-03-27 02:03 UTC
Installed qalculate-3.0.0-x64.msi on Windows 7. When started, it gives the following error message: "The applicaﬁon was unable to start correctly (0xc000007b). Click OK to dose the application." I had no problem with 2.5.0, 2.6.1, 2.6.2, 2.8.0, 2.8.1, or 2.8.2 on this system.

**Comment by hanna-kn** [comment] 2019-03-27 06:43
Are you running 64-bit Windows 7? Otherwise you should install the 32-bit version of Qalculate! ([qalculate-3.0.0-i386.msi](https://github.com/Qalculate/libqalculate/releases/download/v3.0.0/qalculate-3.0.0-i386.msi)).

**Comment by hughh** [comment] 2019-03-27 19:47
Yes, I am running a 64-bit version.

![2019-03-27 15_41_20-Control Panel_All Control Panel Items_System](https://user-images.githubusercontent.com/6372640/55107350-79848800-50a7-11e9-9b1e-721775acee1d.png)

**Comment by hanna-kn** [comment] 2019-03-27 23:01
I am unfortunately unable to reproduce the issue on my Windows 7 Enterprise 64-bit test system.

**Comment by hughh** [comment] 2019-03-30 02:41
I tried downloading the 32-bit version. Running that version, which I believe should work on a 64-bit system, gives the error message, "The program can't start because libidn2-0.dll is missing from your
computer. Try reinstalling the program to ﬁx this problem." Reinstalling the program does NOT fix the problem.

This DLL does exist on my system, in the "C:\Program Files\OpenShot Video Editor\" folder. If this were a Linux system, I'd add simply add this to my library path, but I don't think Windows uses the same process.

**Comment by hanna-kn** [comment] 2019-03-30 07:16
The issue with the 32-bit was my mistake (libidn2-4.dll was included instead; see https://github.com/Qalculate/libqalculate/issues/133). The 32-bit installer was fixed 3 days ago. You will have to download the installer again, or try renaming libidn2-4.dll (in the Qalculate directory) to libidn2-0.dll.

**Comment by hughh** [comment] 2019-03-30 21:09
Thank you, Hanna! Installs and runs without problems now.

**Comment by hanna-kn** [comment] 2019-04-17 10:20
The 64-bit issue is likely fixed now (see issue #92).

**Comment by hughh** [comment] 2019-04-17 19:22
Thank you for your timely attention, Hanna!

**Closed** 2019-06-09 06:48 UTC
