### ISSUE TITLE
Improvement to currency list

### ISSUE THREAD

**Issue by majumeke** [Qalculate/qalculate-gtk#52] opened 2018-04-10 22:30 UTC
Hello, i'm enjoying the vast amount of features in Qalculate! what a great program.

i have a request to make, can you modify the currency list so that all countries have their currency units ? as it is only a few have their full definition(Indian Rupee, Danish Kroner, Swedish Krona, etc) while the majority of currencies are listed by the countries they are used in(Algeria, Benin, Cuba, etc) or alternately could you show me how to modify this information myself ?

Thank you and keep up the great work on Qalculate.

**Comment by hanna-kn** [comment] 2018-04-11 06:32
Each currency needs an entry such as this
```
<builtin_unit name="DKK">
  <_title>Danish Kroner</_title>
  <_names>ar:DKK</_names>
</builtin_unit>
```
in definitions/currencies.xml.in (in the source code) or, without the underscores, in currencies.xml (located in $PREFIX/share/qalculate/ on GNU/Linux).

For currencies with a specific non-conflicting symbol and name, this can specified similar to `<_names>ar:JPY,au:&#xA5;,yen</_names>`.

The reason this has not been done yet, is simply that it requires boring tedious work.

**Comment by majumeke** [comment] 2018-04-23 20:17
ok, have updated the file to the best of my ability. here is the updated file 
[currencies.zip](https://github.com/Qalculate/qalculate-gtk/files/1939833/currencies.zip)
 it is my hope that after you review it you'll update Qalculate! with it. 

a few observations:
- some currencies: Aruban Florin(AWG), Belarusian Ruble(BYN), Maritanian Ouguiya(MRU) and Zambian Kwacha(ZMW) still have their old currency codes: ANG for Aruba, BYR for Belarus, MRO for Mautirius and ZMK for Zambia could you please update Qalculate  to these new codes ? i've already included the new codes in the updated currency list.
- is it possible to expand the list to include all circulating currencies ? i've noticed that some countries like Bhutan, Bonaire, Gabon, Samoa, etc are not on the conversion list.
- some currencies have multiple unicode characters in their symbols like the Saudi Riyal: ر.س which is: &#x0633; &#x002E; &#x0631; in hex. is it possible display these in Qalculate ?
- the list is very long, could you be able to group the currencies according to their first letters ? so that at the very most we have 26 menu items(A-Z) with the countries being in sub-menus.

**Comment by hanna-kn** [comment] 2018-04-24 07:57
- Qalculate! depends on the exchange rates provided by external sources (the currencies you've modified all get their exchange rates from mycurrency.net, the rest from the European Central Bank). These have not yet been updated with the new currencies, but I've added conversions (1 BYN = 10000 BYR, 1 MRU = 10 MRO, 1 ZMW = 1000 ZMK). ANG is used by Curaçao and Sint Maarten.
- Any missing currencies requires additional exchange rate sources (but Gabon uses included XAF and Bonaire uses USD, according to Wikipedia). 
- Multiple Unicode characters can be used, but Arabic characters is a bit problematic.

I've merged your changes, with some modifications (primarily removal of conflicting names), to the git repository.

**Comment by majumeke** [comment] 2018-04-25 19:45
thank you for the merge and the clarifications, the currency list looks much cleaner now. also another question/request. is it possible to add country flags to the currency list ? if possible please guide me on how to add the flags to the list i edited.

**Comment by hanna-kn** [comment] 2018-04-26 09:46
Icons (country flags) cannot be added by editing the XML file.

If you could provide an image file (preferably png) for each flag, with the currency code as file name, it should be possible for me to add the icons to qalculate-gtk using a little bit of code. Currencies used by multiple countries would be problematic.

**Comment by shirishag75** [comment] 2018-04-26 19:28
yup, the first which comes to mind is the Euro :)

**Comment by hanna-kn** [comment] 2018-04-27 07:34
> yup, the first which comes to mind is the Euro :)

It should not be a problem to find an appropriate flag for the Euro, but I'm not so sure about the West and Central African CFA francs.

**Comment by majumeke** [comment] 2018-04-27 13:54
the images with the currency codes as fileneames are attached. for the tricky countries: Chad, Togo, Dominica, etc i've left in the country name. hopefully you can come up with a workaround for these countries.

[Flags.zip](https://github.com/Qalculate/qalculate-gtk/files/1955352/Flags.zip)

images are from:

majority of the flags: http://flaglane.com/category/countries-a-to-z/
european flag: https://europa.eu/european-union/about-eu/symbols/flag_en
all others were from Wikipedia for those that were missing from Flag Lane

**Comment by hanna-kn** [comment] 2018-04-28 05:11
The flag images have now been added to the GUI.

For now I've chosen to not use any flag for XAF, XCD, XOF (as well as obsolete currencies and BTC/XBT). I'm thinking that images with the currency code might be a reasonable alternative for XAF, XCD, XOF (and a variant using the bitcoin symbol for BTC/XBT).

**Comment by majumeke** [comment] 2018-04-30 12:01
very nice. i've attached the flags for countries with obsolete currencies(for reference)

[Flags(Obsolete).zip](https://github.com/Qalculate/qalculate-gtk/files/1960435/Flags.Obsolete.zip)

**Comment by hanna-kn** [comment] 2018-04-30 16:16
I've now added the flags for the obsolete currencies.
I've also added flags for ANG, XAF, XCD, XOF. For ANG I combined placed the two flags side by side in the icon, and for the other three I used the symbol of the corresponding monetary organisation.

**Comment by majumeke** [comment] 2018-05-01 10:16
again, Thank you. now no one is left behind.

another improvement to the currency list would be to enable a user to search the list using the country name, currency name as well as the currency code in both lowercase and uppercase. ideally, this would also apply to tricky countries such as Chad with its XAF code so that a user does not have to know Chad's currency code(XAF) to make a conversion. they would only have to enter Chad/chad for XAF to appear in the selection menu; bonus feature would be to have Chad's flag shown as well.

**Comment by hanna-kn** [comment] 2018-05-02 08:55
> another improvement to the currency list would be to enable a user to search the list using the country name, currency name as well as the currency code in both lowercase and uppercase. ideally, this would also apply to tricky countries such as Chad with its XAF code so that a user does not have to know Chad's currency code(XAF) to make a conversion. they would only have to enter Chad/chad for XAF to appear in the selection menu; bonus feature would be to have Chad's flag shown as well.

Done (for conversion list).

The unit manager still needs some updates

**Comment by majumeke** [comment] 2018-05-03 20:51
lovely, i really appreciate your dedication to making an already excellent software better. Thank you.

**Comment by majumeke** [comment] 2018-05-18 13:04
just installed version 2.5.0 and the currency list looks much cleaner now, Thank you.

would you consider these other improvements as well ?

could the country flag be displayed in the entry box as well ? such that when "dollar to euro" is entered their flags will be displayed in the box in front of their names. 

it would also be great to have the flags appear in the suggestion popup when a currency/country is being typed in.

still with the flags, can the conversion result also have the flag of the country/union displayed in front of the result ? so that when a user carries out a conversion like "HRK to ARS" the result would be: 
≈ Argentinian flag, ARS, result

finally, i still have to type in the currency code for countries instead of the country name or currency name is this still in the works ?

**Comment by hanna-kn** [comment] 2018-05-19 14:56
> could the country flag be displayed in the entry box as well ? such that when "dollar to euro" is entered their flags will be displayed in the box in front of their names.

If you mean the main expression entry, then the answer is an unequivocal no.

> it would also be great to have the flags appear in the suggestion popup when a currency/country is being typed in

The problem with this is that lists where only some items have an icon looks ugly and is a bit distracting. 

> still with the flags, can the conversion result also have the flag of the country/union displayed in front of the result ? so that when a user carries out a conversion like "HRK to ARS" the result would be:
≈ Argentinian flag, ARS, result

It might be difficult to make it look nice and intuitive, and I would argue that the benefit is small. I will try adding a small flag in the upper right corner and see how it looks.

> finally, i still have to type in the currency code for countries instead of the country name or currency name is this in the works ?

There are some issues with implementing that in the expression entry (in addition to the search entries). It is possible to add suggestions based on country and currency name. To avoid long lists dominated by currencies (which is that the reason that most currencies do not show up in the list unless you enter the full code) you will have to enter at least three or four characters of the name for it to show up.

**Comment by hanna-kn** [comment] 2018-05-19 17:01
Improved suggestions and flags in result (when currency code is used) are now done.

**Comment by hanna-kn** [comment] 2018-05-20 10:10
Flags in suggestions list done.

![screenshot 3](https://i.imgur.com/ox1RTcv.png)

**Comment by majumeke** [comment] 2018-05-20 13:39
excellent work, the screenshots look really good. Thank you.

typing in a country name or currency name in addition to currency code is priceless. no more having to remember currency codes or having to type in uppercase to match the code. the flags also make for a consistent experience when dealing with currencies and can also be used as a small learning tool. 

again much appreciated.

**Comment by majumeke** [comment] 2018-06-13 10:22
in 2.6 the country/currency search is much better. i can now type the country name or currency name in any case and get a hit, Thank you. 

i've noticed that you need to type in the first three letters of a country or a currency to get suggestions from the currency list, is this by design ? if i want to get a result for pounds, typing "br" or "po" will not return "British Pounds" in the suggestions but "bri" or "pou" will.

the country flags look really good, i have found an issue though with currencies that display symbols rather than their currency code like the Korean Won.

conversion of Icelandic krona to Algerian dinar

![dinar](https://user-images.githubusercontent.com/26199366/41345468-63ce0144-6f0c-11e8-8c11-b92ade90e0b4.png)


conversion of Icelandic krona to Korean won

![won](https://user-images.githubusercontent.com/26199366/41345487-7aed38e0-6f0c-11e8-8101-6942bddb5238.png)

the flag in the result is not displayed when there is a currency symbol($, €, £, etc)

**Comment by hanna-kn** [comment] 2018-06-13 11:21
> i've noticed that you need to type in the first three letters of a country or a currency to get suggestions from the currency list, is this by design ? if i want to get a result for pounds, typing "br" or "po" will not return "British Pounds" in the suggestions but entering "bri" or "pou" will.

This is by design, to avoid long suggestion lists dominated by currencies. The suggestions would sometimes with have over 100 items that might appear random. The main issue with this approach is that it makes the new feature difficult for users to discover. I'm considering making the completion suggestions configurable.

> the flag in the result is not displayed when there is a currency symbol($, €, £, etc)

This was also a conscious decision. The flags seemed unnecessary and more distracting for common symbols (and spelled out names with abbreviations deactivated). Although for "exotic" currencies, the symbol might be more confusing than the three character code (a possible solution for these relatively few cases would be to give the code higher priority than the symbol).

**Comment by majumeke** [comment] 2018-06-13 13:21
> This is by design, to avoid long suggestion lists dominated by currencies. The suggestions would sometimes with have over 100 items that might appear random. The main issue with this approach is that it makes the new feature difficult for users to discover. 

understood and yes this would be an unfortunate feature to go undiscovered

> I'm considering making the completion suggestions configurable.

personally i believe the sweet spot to be at two letters typed, but the ideal scenario as you mentioned would be to have the suggestions configurable. hopefully your consideration for configurable suggestions becomes concrete.

> This was also a conscious decision. The flags seemed unnecessary and more distracting for common symbols (and spelled out names with abbreviations deactivated). Although for "exotic" currencies, the symbol might be more confusing than the three character code (a possible solution for these relatively few cases would be to give the code higher priority than the symbol).

i have to very respectfully and humbly disagree with this decision. i feel that the flag display should be consistent across symbols and codes. dollars, pounds and euros are common and most people would know the flags of their respective countries/regions but, as you mentioned, we have symbols for currencies such as the Afghan afghani(؋), Armenian dram(֏), Lao kip(₭), Vietnamese dong(₫) that could be seen as being exotic. in my view, having a flag by the symbol would make the currency and its symbol appear less exotic to a casual user. this will ensure a consistent experience to a user used to getting a country flag to go with the currency code also seeing the same with currency symbols. 
another option, as with the proposed configurable suggestion list, would be to make this feature configurable. so that if a user likes to see a country flag along with the currency code/symbol they'll be able to enable this in the settings. a bonus feature would be the ability to configure the location of the flag in the results.

**Comment by hanna-kn** [comment] 2018-06-13 16:35
To my eyes this looks bad:
![Screenshot 1](https://i.imgur.com/r76vI8g.png)

Before I enable flags for symbols I better placement is needed for the flag when the currency is put in front of the number without any space (and I'm not fond of the idea of placing the flag to the left either).

Generally, solving design issues by adding configuration options is a bad idea, so my priority is to improve the default setting.

**Comment by hanna-kn** [comment] 2018-06-13 17:43
I've now implemented a variant where the flag is placed after the number if there is no space between the currency symbol and the number.

**Comment by majumeke** [comment] 2018-06-15 10:49
it doesn't look all that bad to me, but the flag after the number should work too. at least, now, there's consistency in the displaying of these flags. 

Much thanks.

**Comment by majumeke** [comment] 2018-07-10 21:12
just installed version 2.6.1 and i have to give you my sincerest and abundant Thanks. this currency list improvement issue can now be closed as the currency list is now improved by leaps and bounds over my original suggestion. as a bonus the suggestion popup is now more configurable with the new "Completion" preference pane. 
i really appreciate your leniency and quick turnaround in implementing my suggestions in this issue, Thank you.

**Comment by danieldjewell** [comment] 2020-01-08 22:59
Hi All, 

Just noticed something that I found peculiar - I did my best poking around the source to see if I could find it but my knowledge of GTK APIs is seriously lacking ... 

In the Units Editor for Currencies (this is v3.6.0 - the latest win64 build), there appear to be three columns - none have a heading and you can't open the "Edit" dialog to view the details that you normally would be able to. 

The third column (see picture below) has either a "$" or "€" sign in it for every currency except EUR (even USD shows "€") 

In other unit categories, the third column is the definition of the unit (or the base unit)... So does that mean that *all* currencies are being derived from the EUR? And then a bunch more are being derived *twice* (e.g. Saudi Riyal SAR <> USD <> EUR?) 

![image](https://user-images.githubusercontent.com/23286051/72023021-0c557400-322f-11ea-9a58-8f99930e31e9.png)

Thanks!

**Comment by hanna-kn** [comment] 2020-01-09 09:28
> So does that mean that all currencies are being derived from the EUR? And then a bunch more are being derived twice (e.g. Saudi Riyal SAR <> USD <> EUR?).

This is correct. Euro is the currency base unit in Qalculate. The exchange rates in the data from the ECB are provided in relation to EUR, while the mycurrency.net data set uses USD. When converting between currencies (as well as USD) from the mycurrency.net data, additional conversion to EUR is not required. When converting between currencies from different data sources an additional step is however necessary. 

Conversion using exchange rates from both the ECB and mycurrency.net will unfortunately avoidably, because of different update frequencies, result in reduced precision (< 1%). I am considering if it might be beneficial to perform the conversion from USD to EUR directly when loading the data using the rate provided by mycurrency.net (and thus use EUR as the immediate base unit for all currencies).

**Closed** 2021-04-22 07:01 UTC
