### ISSUE TITLE
[Windows OS] slow UI loading time.

### ISSUE THREAD

**Issue by shmaiz** [Qalculate/qalculate-gtk#240] opened 2021-02-17 11:40 UTC
Qalculate version [64-bit installer v3.17]
OS: Windows 10 Pro  64bit
CPU: i5-8250U
RAM: 8GB
Solid Drive [SSD] storage
----------------------------------------

Hello and good day.
First I'd like to thank you very much for this great project.

In my windows system, Qalculate takes almost 3seconds to load. This is very long for an occasional quick use.
Is there a way to reduce the load time?
This is probably an important aspect to enhance in the future for the casual user.

Thanks again !

**Comment by hanna-kn** [comment] 2021-02-17 12:40
Duplicate of #181

**Closed** 2021-02-20 19:22 UTC
