### ISSUE TITLE
Qalculate does not maintain its window position on dual monitor setups

### ISSUE THREAD

**Issue by Gitoffthelawn** [Qalculate/qalculate-gtk#282] opened 2021-05-25 02:29 UTC
On dual monitor setups, the Qalculate window will not maintain it's position if the secondary monitor is toggled on/off.

STR:
1. Turn on *only* primary monitor (secondary monitor off).
2. Open Qalculate.
3. Notice window position.
4. Close Qalculate.
5. Turn on secondary monitor too.
6. Open Qalculate.
7. Notice window position changes from step 3.
8. Close Qalculate.
9. Turn off secondary monitor.
10. Open Qalculate.
11. Notice window position changes from steps 3 and 7.
12. Rinse and repeat.

Test system: Qalculate v3.18.0 on Win7 64-bit

Related: https://github.com/Qalculate/qalculate-gtk/issues/259

**Comment by hanna-kn** [comment] 2021-05-25 06:27
I'm not able to reproduce either issue (this or #259), using two virtual monitors in VirtualBox (I only use one physical monitor and always run Windows on a virtual machine on GNU/Linux).

**Comment by Gitoffthelawn** [comment] 2021-05-25 18:22
@hanna-kn Ya, it doesn't surprise me that VirtualBox virtual monitors don't initially show the issue.

But maybe this will do it:  Try setting the primary virtual monitor to a resolution of 1920x1080, and the secondary virtual monitor to a smaller resolution, say 1366x768.  Now, move the secondary virtual monitor to the left of the primary virtual monitor and align it so the ***bottom*** edges of the two monitors are aligned horizontally.

Often, when I see issues like this, it's because the application is storing an *offset* for the screen position from coordinate **(0,0)**.  Thus, when another monitor is enabled, the physical position of coordinate **(0,0)** changes, causing the offset to now reference a different *physical* position.

**Comment by foreachthing** [comment] 2021-05-25 18:59
Don't connect your monitors via DP... it does that with every application, no?
With my setup it works as expected, because my second monitor is connected via DVI.
As soon as I power off primary monitor (DP) then everything will start switching around - this is either a Windows, nvidia or DP "issue".

**Comment by Gitoffthelawn** [comment] 2021-05-25 19:06
@foreachthing What is DP?  Monitors are all connected via HDMI.  No other issues with any applications besides the one reported here.

**Comment by foreachthing** [comment] 2021-05-25 19:09
> @foreachthing What is DP? Monitors are all connected via HDMI.

DP = Display-Port.
Odd ... but then, I cannot test HDMI, sorry! :-\

**Comment by hanna-kn** [comment] 2021-05-26 07:18
I have now been able to reproduce this issue. Inkscape and MyPaint (both GTK application) exhibit the same behaviour.

**Comment by hanna-kn** [comment] 2021-05-26 11:28
Hopefully fixed now in version 3.19.1.

**Comment by Gitoffthelawn** [comment] 2021-05-26 16:14
Thanks.  I'll try 3.19.1 within 24 hours.

**Comment by Gitoffthelawn** [comment] 2021-05-27 01:03
Works a treat! Thank you!  What did you do?

**Closed** 2021-05-27 01:04 UTC

**Comment by hanna-kn** [comment] 2021-05-27 05:13
> Works a treat! Thank you! What did you do?

Monitor index and window position on the monitor (window position minus monitor workspace position) are now saved. 

There are most likely still some issues when more than two monitors are used (e.g. if the first of three monitors is off). Ideally a unique monitor would be saved, but that is not available in the GTK api (only manufacturer, model, and resolution), but it should be enough to also save if the monitor is set as primary or not.

**Comment by Gitoffthelawn** [comment] 2021-05-27 22:30
Thank you for the details.  I appreciate it.
