### ISSUE TITLE
ukrainian flag

### ISSUE THREAD

**Issue by Tuxomx** [Qalculate/qalculate-gtk#405] opened 2022-04-25 04:18 UTC
I started qalculate after I updated my system yesterday and found a flag in the results window.  It no longer apears after restarting. Also some flags are not shown when converting currencies.  We use a calculator to make calculations, not to get political propaganda this way.

**Comment by hanna-kn** [comment] 2022-04-25 05:39
Duplicate of #389

**Closed by hanna-kn** 2022-04-25 05:39 UTC

**Comment by L1pE** [comment] 2022-04-27 16:38
I am reminded of the case of the node-ipc protestware which started with a simple text file before escalating to corrupting every file in the user's computer. At least calculators are easily replaceable.

**Comment by hanna-kn** [comment] 2022-04-27 17:01
GitHub itself has also made a statement in support of Ukraine (https://github.blog/2022-03-02-our-response-to-the-war-in-ukraine/, with a link in Ukrainian colours on the front page):
- GitHub is united with the people of Ukraine and the international community in condemning these horrific acts of violence against a sovereign nation and its people.

**Comment by L1pE** [comment] 2022-04-27 17:35
If we want to list reasons Github sucks, Github being owned by Microsoft is an even bigger one.

**Comment by ChadFacts** [comment] 2022-05-10 22:59
> GitHub itself has also made a statement in support of Ukraine (https://github.blog/2022-03-02-our-response-to-the-war-in-ukraine/, with a link in Ukrainian colours on the front page):
> 
> > GitHub is united with the people of Ukraine and the international community in condemning these horrific acts of violence against a sovereign nation and its people.

Because GitHub did it doesn't mean you need to. Using that logic, everyone should bomb Ukraine because Russia did it too. Or, countries should all use their own civilians as human meat shields without their knowledge and consequently consent because Ukraine did it too.

But nah, Russia bad amirite. Russia's done bad things but they're not the only government that's committed crimes against human rights.

**Comment by UNIVPM-S1079707** [comment] 2022-05-17 14:53
I was using libqalculate in my rice, but as soon as I've read this I'm going to use calc instead.

I do not want to promote propaganda software.

**Comment by hanna-kn** [comment] 2022-05-17 17:14
> I was using libqalculate in my rice, but as soon as I've read this I'm going to use calc instead until this issue gets fixed.

libqalculate is not affected in any way. If it does what you need, then I certainly do not mind if you use calc instead. (Personally I do not think that I would like the taste of either in my rice.)

The flag will not appear for anyone (not even once for new user of version 4.1 as is now the case) after August (hopefully Russia will have withdrawn by then, but that is probably a bit optimistic).

**Comment by ChadFacts** [comment] 2022-05-17 17:29
> I was using libqalculate in my rice, but as soon as I've read this I'm going to use calc instead until this issue gets fixed.
> 
> I do not want to promote propaganda software.

Seconded. I wish idiots would quit giving into propaganda. It isn't that hard to live your life without being political. People have done it all throughout history.

And if hanna is gonna be political, they should do it properly at least. Engage in political discourse instead of shutting down people who don't want propaganda. At least have the discussion! What's the purpose of propaganda? To push your political agenda and to sway action into people. What better way to do that than to debate with those who are inactive in your cause and convert them to your cause? But hanna isn't doing that. Which shows this is some lame attempt at a political stunt that was half-assed and hanna is too far into their political sphere to not post propaganda.

**Comment by hanna-kn** [comment] 2022-05-17 18:04
> And if hanna is gonna be political, they should do it properly at least. Engage in political discourse instead of shutting down people who don't want propaganda. At least have the discussion! What's the purpose of propaganda? To push your political agenda and to sway action into people. What better way to do that than to debate with those who are inactive in your cause and convert them to your cause?

This is hardly the right forum for proper political discussions. And some are just too far down rabbit to be worth the effort. My aim is not to convert anyone, I only want to try raising awareness and show my support for those affected by the war. At least I want to avoid doing the opposite, and I will certainly not provide a forum for Russian misinformation.

> It isn't that hard to live your life without being political. People have done it all throughout history.

This is just mind-bogglingly stupid. Not being political is a political action in itself (in support of all the delusional egomaniacs in power).
